client_id = 'test-dgvl7g'
client_secret = 'SXocqsUMYE7MONrPm0EHWvSMndJsPpPtEu8dZpkUU19a02S7F111pz8kvORmxyrk'
username = 'tomarovk.irill@gmail.com'
password = '8G7IuS6nOHz0'
log_file = '/home/ws-ivanova-glafira/code/personal/pypodio_microservice/log.py'
